apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

images:
  - name: linuxserver/jackett
    newTag: v0.22.1646-ls708
  - name: linuxserver/sonarr
    newTag: 4.0.14.2939-ls280
  - name: linuxserver/radarr
    newTag: 5.22.4.9896-ls271
  - name: linuxserver/bazarr
    newTag: v1.5.1-ls301
  - name: linuxserver/transmission
    newTag: 4.0.6-r4-ls290
  - name: emby/embyserver
    newTag: 4.9.0.50
  - name: linuxserver/prowlarr
    newTag: 1.34.1.5021-ls115
  - name: lscr.io/linuxserver/readarr
    newTag: nightly-0.4.16.2788-ls395
  - name: lscr.io/linuxserver/jellyfin
    newTag: 10.10.7ubu2404-ls61
  - name: lscr.io/linuxserver/kavita
    newTag: v0.8.6.2-ls78
  - name: lscr.io/linuxserver/lidarr
    newTag: 3.1.0.4875-ls15
