apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: linuxserver/jackett
    newTag: v0.24.545-ls260
  - name: linuxserver/sonarr
    newTag: 4.0.16.2944-ls300
  - name: linuxserver/radarr
    newTag: 6.0.4.10291-ls289
  - name: linuxserver/bazarr
    newTag: v1.5.3-ls329
  - name: linuxserver/transmission
    newTag: 4.0.6-r5-ls322
  - name: emby/embyserver
    newTag: 4.9.4.1
  - name: linuxserver/prowlarr
    newTag: 2.3.0.5236-ls134
  - name: lscr.io/linuxserver/readarr
    newTag: nightly-0.4.16.2788-ls395
  - name: lscr.io/linuxserver/jellyfin
    newTag: 10.11.5ubu2404-ls14
  - name: lscr.io/linuxserver/kavita
    newTag: v0.8.8.3-ls94
  - name: lscr.io/linuxserver/lidarr
    newTag: 3.1.0.4875-ls15
