apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: htpc
spec:
  project: default
  
  source:
    repoURL: https://github.com/fabito/htk8s.git
    targetRevision: master
    path: overlays/x86

  destination:
    server: https://kubernetes.default.svc
    namespace: htpc

  # Sync policy
  syncPolicy:
    automated:
      prune: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/fabito/htk8s.git
    targetRevision: master
    path: argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  # Sync policy
  syncPolicy:
    automated:
      prune: false      
