apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip  
    traefik.ingress.kubernetes.io/frontend-entry-points: http, https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - http:
      paths:
      - path: /argocd
        backend:
          serviceName: argocd-server
          servicePort: http
  tls:
   - secretName: argocd-secret    
