apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: htpc
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: emby
          servicePort: webui
      - path: /jackett
        backend:
          serviceName: jackett
          servicePort: webui
      - path: /sonarr
        backend:
          serviceName: sonarr
          servicePort: webui
      - path: /radarr
        backend:
          serviceName: radarr
          servicePort: webui
      - path: /transmission
        backend:
          serviceName: transmission
          servicePort: webui
