---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: prowlarr
  name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      run: prowlarr
  template:
    metadata:
      labels:
        run: prowlarr
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: chown
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /config"]
        volumeMounts:
        - mountPath: /config
          name: htpc-home
          subPath: prowlarr
      containers:
      - env:
        - name: TZ
          value: Pacific/Auckland
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: PROWLARR__SERVER__URLBASE
          value: /prowlarr
        - name: PROWLARR__AUTH__APIKEY
          valueFrom:
            configMapKeyRef:
              name: arr-apps-api-key
              key: api_key
        image: linuxserver/prowlarr
        name: prowlarr
        ports:
        - containerPort: 9696
          name: webui
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl "http://localhost:9696/prowlarr/api/v1/health?ApiKey=$(PROWLARR__AUTH__APIKEY)"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl "http://localhost:9696/prowlarr/api/v1/system/status?ApiKey=$(PROWLARR__AUTH__APIKEY)"
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - mountPath: /config
          name: htpc-home
          subPath: prowlarr
