name: Upgrade Apps

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup tools
        uses: ./.github/actions/tools
        with:
          yq_version: "v4.20.2"

      - name: Upgrade apps
        id: upgrade
        run: make upgrade-apps

      - name: Update manifests
        if: steps.upgrade.outputs.apps_updated == 'true'
        run: make manifests

      - name: Create Pull Request
        if: steps.upgrade.outputs.apps_updated == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: ${{ steps.upgrade.outputs.commit_message }}
          title: 'chore(apps): bump to latest versions'
          body: 'This is an automated pull request to upgrade the installed apps.'
          branch: 'feat/automate-app-upgrades'
