name: Upgrade Apps

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install yq
        run: pip install yq

      - name: Upgrade apps and manifests
        run: |
          make upgrade-apps
          make manifests

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'feat: Automate app upgrades'
          title: 'Automated App Upgrades'
          body: 'This is an automated pull request to upgrade the installed apps.'
          branch: 'feat/automate-app-upgrades'
